name: prd-env
on:
  push:
    branches:
      - prd
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/naturegecko/bookinfo-ratings:dev
  deploy-prd:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: get-credentials
        uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: k8s
          location: asia-southeast1-a
          credentials: ${{ secrets.GKE_CREDENTIALS }}
      - name: deploy
        uses: deliverybot/helm@v1
        with:
          helm: helm3
          release: bookinfo-prd-ratings
          namespace: student32-bookinfo-prd
          chart: k8s/helm
          value-files: k8s/helm-values/values-bookinfo-prd-ratings.yaml
          values: |
            {
              "extraEnv": {
                "COMMIT_SHA": "${{ github.sha }}"
              }
            }    
  check-health:
    needs: deploy-prd
    runs-on: ubuntu-20.04
    steps:
    - name: Acceptance Test
      run : curl http://bookinfo.opsta.net/student32/ratings/health | grep "Ratings is working"